# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'oct_main_window.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 965)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("icons/633563-basic-icons/png/233-empty.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.mdiArea = QtGui.QMdiArea(self.centralwidget)
        self.mdiArea.setObjectName(_fromUtf8("mdiArea"))
        self.subwindowScanViewer = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.subwindowScanViewer.sizePolicy().hasHeightForWidth())
        self.subwindowScanViewer.setSizePolicy(sizePolicy)
        self.subwindowScanViewer.setObjectName(_fromUtf8("subwindowScanViewer"))
        self.gridLayout_3 = QtGui.QGridLayout(self.subwindowScanViewer)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.graphicsView = QtGui.QGraphicsView(self.subwindowScanViewer)
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.gridLayout_3.addWidget(self.graphicsView, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.spinBoxSliceNumber = QtGui.QSpinBox(self.subwindowScanViewer)
        self.spinBoxSliceNumber.setObjectName(_fromUtf8("spinBoxSliceNumber"))
        self.horizontalLayout_3.addWidget(self.spinBoxSliceNumber)
        self.toolButtonLockView = QtGui.QToolButton(self.subwindowScanViewer)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("icons/633563-basic-icons/png/131-link.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonLockView.setIcon(icon1)
        self.toolButtonLockView.setObjectName(_fromUtf8("toolButtonLockView"))
        self.horizontalLayout_3.addWidget(self.toolButtonLockView)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.subwindowToolBox = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.subwindowToolBox.sizePolicy().hasHeightForWidth())
        self.subwindowToolBox.setSizePolicy(sizePolicy)
        self.subwindowToolBox.setMinimumSize(QtCore.QSize(240, 400))
        self.subwindowToolBox.setMaximumSize(QtCore.QSize(240, 400))
        self.subwindowToolBox.setObjectName(_fromUtf8("subwindowToolBox"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.subwindowToolBox)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.groupBox = QtGui.QGroupBox(self.subwindowToolBox)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.comboBoxEditMap = QtGui.QComboBox(self.groupBox)
        self.comboBoxEditMap.setObjectName(_fromUtf8("comboBoxEditMap"))
        self.comboBoxEditMap.addItem(_fromUtf8(""))
        self.comboBoxEditMap.addItem(_fromUtf8(""))
        self.comboBoxEditMap.addItem(_fromUtf8(""))
        self.verticalLayout_5.addWidget(self.comboBoxEditMap)
        self.verticalLayout_6.addWidget(self.groupBox)
        spacerItem = QtGui.QSpacerItem(20, 18, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        self.verticalLayout_6.addItem(spacerItem)
        self.groupBoxOpacity = QtGui.QGroupBox(self.subwindowToolBox)
        self.groupBoxOpacity.setObjectName(_fromUtf8("groupBoxOpacity"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBoxOpacity)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.horizontalLayoutBscan = QtGui.QHBoxLayout()
        self.horizontalLayoutBscan.setObjectName(_fromUtf8("horizontalLayoutBscan"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.groupBoxOpacity)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtGui.QLabel(self.groupBoxOpacity)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtGui.QLabel(self.groupBoxOpacity)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayoutBscan.addLayout(self.verticalLayout)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalSlider = QtGui.QSlider(self.groupBoxOpacity)
        self.horizontalSlider.setMaximum(255)
        self.horizontalSlider.setPageStep(10)
        self.horizontalSlider.setTracking(True)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setTickPosition(QtGui.QSlider.NoTicks)
        self.horizontalSlider.setObjectName(_fromUtf8("horizontalSlider"))
        self.verticalLayout_4.addWidget(self.horizontalSlider)
        self.horizontalSlider_2 = QtGui.QSlider(self.groupBoxOpacity)
        self.horizontalSlider_2.setMaximum(255)
        self.horizontalSlider_2.setPageStep(10)
        self.horizontalSlider_2.setTracking(True)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setTickPosition(QtGui.QSlider.NoTicks)
        self.horizontalSlider_2.setObjectName(_fromUtf8("horizontalSlider_2"))
        self.verticalLayout_4.addWidget(self.horizontalSlider_2)
        self.horizontalSlider_3 = QtGui.QSlider(self.groupBoxOpacity)
        self.horizontalSlider_3.setMaximum(255)
        self.horizontalSlider_3.setPageStep(10)
        self.horizontalSlider_3.setTracking(True)
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setTickPosition(QtGui.QSlider.NoTicks)
        self.horizontalSlider_3.setObjectName(_fromUtf8("horizontalSlider_3"))
        self.verticalLayout_4.addWidget(self.horizontalSlider_3)
        self.horizontalLayoutBscan.addLayout(self.verticalLayout_4)
        self.gridLayout_2.addLayout(self.horizontalLayoutBscan, 0, 0, 1, 1)
        self.horizontalLayoutEnface = QtGui.QHBoxLayout()
        self.horizontalLayoutEnface.setObjectName(_fromUtf8("horizontalLayoutEnface"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_4 = QtGui.QLabel(self.groupBoxOpacity)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_2.addWidget(self.label_4)
        self.label_5 = QtGui.QLabel(self.groupBoxOpacity)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_2.addWidget(self.label_5)
        self.horizontalLayoutEnface.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalSlider_4 = QtGui.QSlider(self.groupBoxOpacity)
        self.horizontalSlider_4.setMaximum(255)
        self.horizontalSlider_4.setPageStep(10)
        self.horizontalSlider_4.setTracking(True)
        self.horizontalSlider_4.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_4.setTickPosition(QtGui.QSlider.NoTicks)
        self.horizontalSlider_4.setObjectName(_fromUtf8("horizontalSlider_4"))
        self.verticalLayout_3.addWidget(self.horizontalSlider_4)
        self.horizontalSlider_5 = QtGui.QSlider(self.groupBoxOpacity)
        self.horizontalSlider_5.setMaximum(255)
        self.horizontalSlider_5.setPageStep(10)
        self.horizontalSlider_5.setTracking(True)
        self.horizontalSlider_5.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_5.setTickPosition(QtGui.QSlider.NoTicks)
        self.horizontalSlider_5.setObjectName(_fromUtf8("horizontalSlider_5"))
        self.verticalLayout_3.addWidget(self.horizontalSlider_5)
        self.horizontalLayoutEnface.addLayout(self.verticalLayout_3)
        self.gridLayout_2.addLayout(self.horizontalLayoutEnface, 1, 0, 1, 1)
        self.verticalLayout_6.addWidget(self.groupBoxOpacity)
        spacerItem1 = QtGui.QSpacerItem(20, 18, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        self.verticalLayout_6.addItem(spacerItem1)
        self.groupBoxToolBox = QtGui.QGroupBox(self.subwindowToolBox)
        self.groupBoxToolBox.setObjectName(_fromUtf8("groupBoxToolBox"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBoxToolBox)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.toolButtonPencil = QtGui.QToolButton(self.groupBoxToolBox)
        self.toolButtonPencil.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("icons/633563-basic-icons/png/085-pencil.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonPencil.setIcon(icon2)
        self.toolButtonPencil.setObjectName(_fromUtf8("toolButtonPencil"))
        self.gridLayout_4.addWidget(self.toolButtonPencil, 0, 0, 1, 1)
        self.toolButtonEraser = QtGui.QToolButton(self.groupBoxToolBox)
        self.toolButtonEraser.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("icons/633563-basic-icons/png/017-usb-1.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonEraser.setIcon(icon3)
        self.toolButtonEraser.setObjectName(_fromUtf8("toolButtonEraser"))
        self.gridLayout_4.addWidget(self.toolButtonEraser, 0, 1, 1, 1)
        self.toolButtonMagnifier = QtGui.QToolButton(self.groupBoxToolBox)
        self.toolButtonMagnifier.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("icons/633563-basic-icons/png/059-loupe.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonMagnifier.setIcon(icon4)
        self.toolButtonMagnifier.setObjectName(_fromUtf8("toolButtonMagnifier"))
        self.gridLayout_4.addWidget(self.toolButtonMagnifier, 0, 2, 1, 1)
        self.toolButtonHome = QtGui.QToolButton(self.groupBoxToolBox)
        self.toolButtonHome.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("icons/633563-basic-icons/png/144-home.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonHome.setIcon(icon5)
        self.toolButtonHome.setObjectName(_fromUtf8("toolButtonHome"))
        self.gridLayout_4.addWidget(self.toolButtonHome, 0, 3, 1, 1)
        self.toolButtonUndo = QtGui.QToolButton(self.groupBoxToolBox)
        self.toolButtonUndo.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("icons/633563-basic-icons/png/064-previous.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonUndo.setIcon(icon6)
        self.toolButtonUndo.setObjectName(_fromUtf8("toolButtonUndo"))
        self.gridLayout_4.addWidget(self.toolButtonUndo, 1, 0, 1, 1)
        self.toolButtonRedo = QtGui.QToolButton(self.groupBoxToolBox)
        self.toolButtonRedo.setText(_fromUtf8(""))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8("icons/633563-basic-icons/png/232-next-2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonRedo.setIcon(icon7)
        self.toolButtonRedo.setObjectName(_fromUtf8("toolButtonRedo"))
        self.gridLayout_4.addWidget(self.toolButtonRedo, 1, 1, 1, 1)
        self.toolButtonRelod = QtGui.QToolButton(self.groupBoxToolBox)
        self.toolButtonRelod.setText(_fromUtf8(""))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8("icons/633563-basic-icons/png/067-reload.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonRelod.setIcon(icon8)
        self.toolButtonRelod.setObjectName(_fromUtf8("toolButtonRelod"))
        self.gridLayout_4.addWidget(self.toolButtonRelod, 1, 2, 1, 1)
        self.toolButtonUnlock = QtGui.QToolButton(self.groupBoxToolBox)
        self.toolButtonUnlock.setText(_fromUtf8(""))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8("icons/633563-basic-icons/png/007-broken-link.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonUnlock.setIcon(icon9)
        self.toolButtonUnlock.setObjectName(_fromUtf8("toolButtonUnlock"))
        self.gridLayout_4.addWidget(self.toolButtonUnlock, 1, 3, 1, 1)
        self.verticalLayout_6.addWidget(self.groupBoxToolBox)
        self.gridLayout.addWidget(self.mdiArea, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 27))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName(_fromUtf8("menu_File"))
        self.menu_Edit = QtGui.QMenu(self.menubar)
        self.menu_Edit.setObjectName(_fromUtf8("menu_Edit"))
        self.menu_View = QtGui.QMenu(self.menubar)
        self.menu_View.setObjectName(_fromUtf8("menu_View"))
        self.menu_Window = QtGui.QMenu(self.menubar)
        self.menu_Window.setObjectName(_fromUtf8("menu_Window"))
        self.menu_Help = QtGui.QMenu(self.menubar)
        self.menu_Help.setObjectName(_fromUtf8("menu_Help"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBarBasic = QtGui.QToolBar(MainWindow)
        self.toolBarBasic.setObjectName(_fromUtf8("toolBarBasic"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBarBasic)
        self.toolBarOCTperdiction = QtGui.QToolBar(MainWindow)
        self.toolBarOCTperdiction.setObjectName(_fromUtf8("toolBarOCTperdiction"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBarOCTperdiction)
        self.toolBarExtraAnalysis = QtGui.QToolBar(MainWindow)
        self.toolBarExtraAnalysis.setObjectName(_fromUtf8("toolBarExtraAnalysis"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBarExtraAnalysis)
        self.action_Open = QtGui.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8("icons/633563-basic-icons/png/153-folder.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Open.setIcon(icon10)
        self.action_Open.setObjectName(_fromUtf8("action_Open"))
        self.action_Save = QtGui.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8("icons/633563-basic-icons/png/060-diskette.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Save.setIcon(icon11)
        self.action_Save.setObjectName(_fromUtf8("action_Save"))
        self.action_Toolbox = QtGui.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8("icons/633563-basic-icons/png/086-school-material.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Toolbox.setIcon(icon12)
        self.action_Toolbox.setObjectName(_fromUtf8("action_Toolbox"))
        self.action_Reset = QtGui.QAction(MainWindow)
        self.action_Reset.setObjectName(_fromUtf8("action_Reset"))
        self.actionFindLayers = QtGui.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8("icons/633563-basic-icons/png/005-wifi-2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFindLayers.setIcon(icon13)
        self.actionFindLayers.setObjectName(_fromUtf8("actionFindLayers"))
        self.actionFindDrusen = QtGui.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8("icons/633563-basic-icons/png/192-cloud.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFindDrusen.setIcon(icon14)
        self.actionFindDrusen.setObjectName(_fromUtf8("actionFindDrusen"))
        self.actionShowEnface = QtGui.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8("icons/633563-basic-icons/png/015-user-1.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionShowEnface.setIcon(icon15)
        self.actionShowEnface.setObjectName(_fromUtf8("actionShowEnface"))
        self.actionShowEnfaceDrusen = QtGui.QAction(MainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(_fromUtf8("icons/633563-basic-icons/png/220-arroba.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionShowEnfaceDrusen.setIcon(icon16)
        self.actionShowEnfaceDrusen.setObjectName(_fromUtf8("actionShowEnfaceDrusen"))
        self.actionShow3D = QtGui.QAction(MainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(_fromUtf8("icons/633563-basic-icons/png/177-cube.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionShow3D.setIcon(icon17)
        self.actionShow3D.setObjectName(_fromUtf8("actionShow3D"))
        self.actionMeasureDrusen = QtGui.QAction(MainWindow)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(_fromUtf8("icons/633563-basic-icons/png/189-analytics.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMeasureDrusen.setIcon(icon18)
        self.actionMeasureDrusen.setObjectName(_fromUtf8("actionMeasureDrusen"))
        self.menu_File.addAction(self.action_Open)
        self.menu_File.addAction(self.action_Save)
        self.menu_View.addAction(self.action_Toolbox)
        self.menu_Window.addAction(self.action_Reset)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Edit.menuAction())
        self.menubar.addAction(self.menu_View.menuAction())
        self.menubar.addAction(self.menu_Window.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())
        self.toolBarBasic.addAction(self.action_Open)
        self.toolBarBasic.addAction(self.action_Save)
        self.toolBarOCTperdiction.addAction(self.actionFindLayers)
        self.toolBarOCTperdiction.addAction(self.actionFindDrusen)
        self.toolBarOCTperdiction.addAction(self.actionShowEnface)
        self.toolBarOCTperdiction.addAction(self.actionShowEnfaceDrusen)
        self.toolBarOCTperdiction.addAction(self.action_Toolbox)
        self.toolBarExtraAnalysis.addAction(self.actionShow3D)
        self.toolBarExtraAnalysis.addAction(self.actionMeasureDrusen)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "OCT Editor", None))
        self.subwindowScanViewer.setWindowTitle(_translate("MainWindow", "Viewer", None))
        self.toolButtonLockView.setText(_translate("MainWindow", "...", None))
        self.subwindowToolBox.setWindowTitle(_translate("MainWindow", "Toolbox", None))
        self.groupBox.setTitle(_translate("MainWindow", "Edit", None))
        self.comboBoxEditMap.setItemText(0, _translate("MainWindow", "Layer map", None))
        self.comboBoxEditMap.setItemText(1, _translate("MainWindow", "Drusen map", None))
        self.comboBoxEditMap.setItemText(2, _translate("MainWindow", "Enface drusen map", None))
        self.groupBoxOpacity.setTitle(_translate("MainWindow", "Opacity", None))
        self.label.setText(_translate("MainWindow", "B-Scan", None))
        self.label_2.setText(_translate("MainWindow", "Layer map", None))
        self.label_3.setText(_translate("MainWindow", "Drusen map", None))
        self.label_4.setText(_translate("MainWindow", "Enface", None))
        self.label_5.setText(_translate("MainWindow", "Enface drusen", None))
        self.groupBoxToolBox.setTitle(_translate("MainWindow", "Toolbox", None))
        self.menu_File.setTitle(_translate("MainWindow", "&File", None))
        self.menu_Edit.setTitle(_translate("MainWindow", "&Edit", None))
        self.menu_View.setTitle(_translate("MainWindow", "&View", None))
        self.menu_Window.setTitle(_translate("MainWindow", "&Window", None))
        self.menu_Help.setTitle(_translate("MainWindow", "&Help", None))
        self.toolBarBasic.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.toolBarOCTperdiction.setWindowTitle(_translate("MainWindow", "toolBar_2", None))
        self.toolBarExtraAnalysis.setWindowTitle(_translate("MainWindow", "toolBar_3", None))
        self.action_Open.setText(_translate("MainWindow", "&Open", None))
        self.action_Save.setText(_translate("MainWindow", "&Save", None))
        self.action_Toolbox.setText(_translate("MainWindow", "&Toolbox", None))
        self.action_Reset.setText(_translate("MainWindow", "&Reset", None))
        self.actionFindLayers.setText(_translate("MainWindow", "FindLayers", None))
        self.actionFindLayers.setToolTip(_translate("MainWindow", "Find layers", None))
        self.actionFindDrusen.setText(_translate("MainWindow", "findDrusen", None))
        self.actionFindDrusen.setToolTip(_translate("MainWindow", "Find Drusen", None))
        self.actionShowEnface.setText(_translate("MainWindow", "showEnface", None))
        self.actionShowEnface.setToolTip(_translate("MainWindow", "Show Enface", None))
        self.actionShowEnfaceDrusen.setText(_translate("MainWindow", "showEnfaceDrusen", None))
        self.actionShowEnfaceDrusen.setToolTip(_translate("MainWindow", "Show enface drusen", None))
        self.actionShow3D.setText(_translate("MainWindow", "show3D", None))
        self.actionShow3D.setToolTip(_translate("MainWindow", "Show PED volume", None))
        self.actionMeasureDrusen.setText(_translate("MainWindow", "measureDrusen", None))
        self.actionMeasureDrusen.setToolTip(_translate("MainWindow", "Measure Drusen", None))

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

